# Generated by Django 4.0.2 on 2022-04-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professeur', '0002_professeur_dernierdiplomeuniversitaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='updated_at',
        ),
    ]
