# Generated by Django 4.0.2 on 2022-05-03 20:25

from django.db import migrations, models
import professeur.models


class Migration(migrations.Migration):

    dependencies = [
        ('professeur', '0003_remove_professeur_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to=professeur.models.Professeur.upload_path),
        ),
    ]
