# Generated by Django 4.0.2 on 2022-05-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeur', '0004_professeur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
