# Generated by Django 4.0.2 on 2022-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeur', '0005_alter_professeur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='departement',
            field=models.IntegerField(null=True),
        ),
    ]
