# Generated by Django 4.0.2 on 2022-05-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeur', '0006_alter_professeur_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='image',
            field=models.ImageField(default='images/professeur/default.png', upload_to='images/'),
        ),
    ]
