# Generated by Django 4.0.2 on 2022-05-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topManageur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmanageur',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
