# Generated by Django 4.0.2 on 2022-05-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='VilleDepart',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='dateNaissance',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
