# Generated by Django 4.0.2 on 2022-05-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_remove_etudiant_villedepart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='VilleDepart',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='dateNaissance',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
