# Generated by Django 4.0.2 on 2022-04-30 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Permanent', 'Permanent'), ('Affilié', 'Affilié'), ('Vacataire', 'Vacataire'), ('Prestataire', 'Prestataire')], max_length=50, null=True)),
                ('dateNaissance', models.CharField(max_length=50, null=True)),
                ('grade', models.CharField(max_length=50, null=True)),
                ('DernierDiplomeUniversitaire', models.CharField(max_length=50, null=True)),
                ('VilleDepart', models.CharField(max_length=50, null=True)),
                ('departement', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinateur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
