# Generated by Django 4.0.2 on 2022-05-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinateur', '0003_alter_coordinateur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinateur',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
